export const SET_AUTH_USER = 'SET_AUTH_USER';
export const SET_CART_ITEMS = 'SET_CART_ITEMS';
export const REMOVE_CART_ITEMS = 'REMOVE_CART_ITEMS';
export const DELETE_CART_ITEMS = 'DELETE_CART_ITEMS';
export const SET_USER_ADDRESS = 'SET_USER_ADDRESS';